#Set the delay (in seconds) for the players to leave combat
delay: 10.0

#Wether or not drinking a potion will put players in combat
is-potion-fighting: false

#If set to true, drinking any potion will put players in combat
any-potion: false

#List of all the potion effects that would put a player in combat if any-potion is set to false
#You can find a list of all the potion types here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/potion/PotionType.html
potion-list:
  - STRENGTH
